#Name of the GitHub Action
name: Test-Build

#Set the action on which the workflow will trigger
on:
 push:
   branches:
     - master
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    #Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@master
      # Install Node.js environment
    - name: set up node
      uses: actions/setup-node@v1
      with:
          node-version: '12.x'

# Install newman
    - name: Install newman
      run: | 
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    - name: Run POSTMAN collection
      run: |
       newman run "Subscription API.postman_collection.json" -e "New Prod Subscription API.postman_environment.json" --verbose
       
